### ISSUE TITLE
Issue with  rtf-utilities/scripts/test_flanneld.sh after upgrading appliance to latest

### ISSUE THREAD

**Issue by sbhakta99** [mulesoft-labs/rtf-utilities#2]
Issue with running rtf-utilities/scripts/test_flanneld.sh after upgrading appliance to latest (1.1.1588363273-4110aff), same scripted worked fine with 1.1.1586472858-1609d2f version.

Article: https://help.mulesoft.com/s/article/How-to-Check-if-the-Overlay-Network-is-Working-Well-in-RTF

parse error: Invalid numeric literal at line 1, column 7
parse error: Invalid numeric literal at line 1, column 7
./test_flanneld.sh: line 65: [: !=: unary operator expected
parse error: Invalid numeric literal at line 1, column 7
parse error: Invalid numeric literal at line 1, column 7
./test_flanneld.sh: line 65: [: !=: unary operator expected
parse error: Invalid numeric literal at line 1, column 7
parse error: Invalid numeric literal at line 1, column 7
./test_flanneld.sh: line 65: [: !=: unary operator expected
parse error: Invalid numeric literal at line 1, column 7
parse error: Invalid numeric literal at line 1, column 7
./test_flanneld.sh: line 65: [: !=: unary operator expected
parse error: Invalid numeric literal at line 1, column 7
parse error: Invalid numeric literal at line 1, column 7
./test_flanneld.sh: line 65: [: !=: unary operator expected
parse error: Invalid numeric literal at line 1, column 7
parse error: Invalid numeric literal at line 1, column 7
./test_flanneld.sh: line 65: [: !=: unary operator expected

**Comment by yuxiaojian** [comment]
It looks like because of "jq" is not available. The latest version runs the jq inside the planet. Please give it a try

**Comment by sbhakta99** [comment]
We did have jq installed on the system.  Appears someone has recently updated it and new script works.  Thank you.
